### ISSUE TITLE
Loops infinite games since I tried to add an endgame GUId

### ISSUE THREAD

**Issue by hippi345** [hippi345/randobotjava#17]
I am not sure why this is infinitely looping through games. My goal was to create a new GUI for either starting a new game or exiting.

https://github.com/hippi345/randobotjava/blob/56a8f1e5d83da8b58531c4d22863c4c67e596be7/src/sample/View.java#L229-L248

**Comment by RiskRunner0** [comment]
What's the branch?

**Comment by hippi345** [comment]
endGameGUI

**Comment by hippi345** [comment]
@QueenCitySmitty 
I implemented a quick fix to at least stop the endless looping but the issue is that the end game gui never pops up and the game gui does not close. 
See the latest branch around the same area of code in View.java.

**Comment by RiskRunner0** [comment]
Okay, here's the issue:

Master
https://github.com/hippi345/randobotjava/blob/b5aae0afa324f71cdbd89eed2486a5d3a8c8c648/src/sample/Game.java#L49-L53

On your first commit for endGameGui 56a8f1e5d83da8b58531c4d22863c4c67e596be7, you removed the ```System.exit();```.  I bet you were using autoplay to have this come up.  Now, on autoplay, when the treasure isn't found, it just continuously loops since there's no exit case.  If you use the arrow keys, the window will come up.

**Comment by hippi345** [comment]
Pushed new commit to endGameGui to allow this bug to go away at least for now so further development and testing can be done with the game breaking
Autoplay will die out with system.exit and manual will show the end game screen which needs some fixes
I will continue to work on making this stable for both game types and have the end game screen be bug free.
Will open a new issue if future bugs come up.
