### ISSUE TITLE
Review Request

### ISSUE THREAD

**Issue by hippi345** [hippi345/randobotjava#18]
Just wanted to present this for fix review on endGameGui latest commit and how the bug was patched up to allow for future development to proceed without the game breaking - this was suggested per a previous issue submitted by me.

https://github.com/hippi345/randobotjava/blob/37eb8f143031907d31a48e7359b2276c05399935/src/sample/Game.java#L36-L76

**Comment by RiskRunner0** [comment]
As of now, is there any difference between an automove, and a move determined by the bot?  To me, the game doesn't differentiate, and to invert control, we could have a public method to get the status of the game, like "In Progress" or "Complete".  That way we could have like (currently in Main.java):
```java
static void RunAutoPlay()
{
    while(game.Status != GameStatusEnum.Complete)
    {
        game.executeMove();
    }
}
```

THAT way, we could try to uncouple the game from the view, that would be a good step forward.  I think we should think of what the interface for IGame should look like, and try to program against that.  Especially because like in the future, what's going to constitute as a "complete game"?  Like right now, it's just finding a treasure, but if we have multiple treasures, we're going to have to switch up a lot of that logic.  Storing the status in a field might be a good solution.

**Comment by hippi345** [comment]
Resolved in most recent PR on endGameGui - awaiting review - recommendations are valid for future scaling implementations and should be added as tasks
